version: '3.8'  # Specify the version

services:
  db:
    container_name: postgres-idv
    image: postgres:latest
    environment:
      POSTGRES_USER: idv
      POSTGRES_PASSWORD: idv
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db-network
    restart: unless-stopped

networks:
  db-network:  # This should be at the root level

volumes:
  db:  # If you're using volumes, define it explicitly
